### ISSUE TITLE
Configuration screen won't show up

### ISSUE THREAD

**Issue by toomanynights** [ReallyLiri/googlogs-vscode#1]
Hey,
A great idea for the app, but for some reason I can't get it to work.
When I install it, no matter if it's 0.0.6 from here or 0.0.7 from the marketplace, the only screen it shows is "No cloud projects found". I have a project but I can't see any place to specify it.
Maybe I'm doing something wrong? Is there a config somewhere I should edit?
Thanks!

**Comment by ReallyLiri** [comment]
Hi, thanks for your interest!
A custom or configurable auth was not implemented yet.
Currently the plugin uses the token it receives from `gcloud auth print-access-token`
Can you check the output of this command and which user account it belongs to?

**Comment by toomanynights** [comment]
Ah, that explains it. I didn't have gcloud installed - had no use for it since I use clasp for authorization.
Any reason why it could return "No logs found 😔 Try to refine your search" while there are definitely logs present? I can see them in https://console.cloud.google.com/logs but not in googlogs.

**Comment by ReallyLiri** [comment]
> Ah, that explains it. I didn't have gcloud installed - had no use for it since I use clasp for authorization. Any reason why it could return "No logs found 😔 Try to refine your search" while there are definitely logs present? I can see them in [console.cloud.google.com/logs](https://console.cloud.google.com/logs) but not in googlogs.

Probably the filtering doesn't match, can you try to extract runtime logs of the app so we can tell exactly which requests it makes to the api?
Should be present in the console log: "Help"->"Toggle Developer Tools" and/or in regular output console: https://stackoverflow.com/a/65938179/1236401

**Comment by toomanynights** [comment]
I currently have all possible filters disabled. One thing I have to choose is project. According to the link in Dev tools, the following query is performed:
`resource.type="k8s_container" AND timestamp>="2023-10-15T13:17:21Z"`
resource.type seems to be hard coded, I can't remove this filter in the interface. If I remove it in google Cloud interface, I can see the logs.

**Comment by ReallyLiri** [comment]
Indeed the source is hardcoded, as my main use case was GKE logs. However there's no good reason to limit it as such.
Will work on allowing to configure the resource type. I currently don't have access to a live GCP environment, so might take a bit. Thanks 🙏

**Comment by ReallyLiri** [comment]
@toomanynights I published a new version `v0.0.8` that allows configuring the resource type (or leaving it empty). As mentioned, couldn't properly test it, can you please check?

**Comment by toomanynights** [comment]
Resource type can certainly be configured now, but that changes little unfortunately :(
https://imgur.com/a/A4tmFYR
Interesting thing is, it says "showing 200 results" and then shows none. When I "Open in web", the logs are displayed correctly without any altering of the query.

**Comment by ReallyLiri** [comment]
Can you try to edit the `schema` field in the search options to `.`? It should then return the whole log line and not attempt to parse it, although I haven't tested it on enough cases. Can you paste here some example log lines if that doesn't work?

Also, its possible but unlikely that your logs are in protobuf payload. That payload is not supported at the moment at all

<img width="550" alt="image" src="https://github.com/ReallyLiri/googlogs-vscode/assets/16985735/21e63e94-d070-4408-a463-770ad1a7e6d6">

**Comment by toomanynights** [comment]
Hey, sorry it took me a while. It's funny, dot or no dot, or whatever I put into "Schema", every line looks exactly like contents of "Schema" field. For example, here it is with 10 dots.
![изображение](https://github.com/ReallyLiri/googlogs-vscode/assets/17919262/5878d1fc-46e7-46ab-a1a5-7df68a25c4fa)

**Comment by ReallyLiri** [comment]
I was finally able to debug the issue and see why it didn't work. v0.0.9 was published, where empty schema should work for you! please check :)

**Comment by toomanynights** [comment]
It does show logs now! But they look like unparsed JSON's, hardly readable :( On the screen capture from your page on the market I saw a bit more handy format, how could I achieve it?

**Comment by ReallyLiri** [comment]
Yes, without schema the raw logs will be displayed. The schema is there to parse out specific properties out of the json. i.e the default schema was created with such log lines in mind:

```
.timestamp [.severity] .jsonPayload.caller .jsonPayload.mdc - .jsonPayload.message - .jsonPayload.e
```

```
    {
      "insertId": "hej2q46u808lwlua",
      "jsonPayload": {
        "e": "java.lang.NullPointerException: Cannot invoke \"String.toLowerCase(java.util.Locale)\" because the return value of \"java.net.URI.getHost()\" is null\n\tat com.acme.reactor.utils.PermalinkUtils.sanitizeUrl(PermalinkUtils.java:17)\n\tat com.acme.reactor.nlp.LinksExtractor.handleUrl(LinksExtractor.java:52)\n\tat com.acme.reactor.nlp.LinksExtractor.lambda$extractConversationLinks$0(LinksExtractor.java:30)\n\tat java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)\n\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:3213)\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)\n\tat java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)\n\tat java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)\n\tat java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)\n\tat com.acme.reactor.nlp.LinksExtractor.extractConversationLinks(LinksExtractor.java:22)\n\tat com.acme.reactor.model.Conversation.updateConversationWithMessage(Conversation.java:106)\n\tat com.acme.reactor.model.ConversationsSnapshot.handleMessage(ConversationsSnapshot.java:113)\n\tat com.acme.reactor.service.ConversationHandler.lambda$handleMessage$2(ConversationHandler.java:105)\n\tat java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1940)\n\tat com.acme.reactor.service.ConversationHandler.handleMessage(ConversationHandler.java:101)\n\tat com.acme.reactor.service.MessageEventHandler.handle(MessageEventHandler.java:40)\n\tat com.acme.reactor.messaging.kafka.ReactorKafkaConsumer.lambda$onMessage$1(ReactorKafkaConsumer.java:61)\n\tat com.acme.datalib.messaging.kafka.KafkaConsumer.handleMessage(KafkaConsumer.java:44)\n\tat com.acme.reactor.messaging.kafka.ReactorKafkaConsumer.onMessage(ReactorKafkaConsumer.java:51)\n\tat jdk.internal.reflect.GeneratedMethodAccessor167.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:567)\n\tat org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169)\n\tat org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119)\n\tat org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:56)\n\tat org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:347)\n\tat org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter.invoke(BatchMessagingMessageListenerAdapter.java:180)\n\tat org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter.onMessage(BatchMessagingMessageListenerAdapter.java:172)\n\tat org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter.onMessage(BatchMessagingMessageListenerAdapter.java:61)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchOnMessage(KafkaMessageListenerContainer.java:2268)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchOnMessageWithRecordsOrList(KafkaMessageListenerContainer.java:2258)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchOnMessage(KafkaMessageListenerContainer.java:2204)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchListener(KafkaMessageListenerContainer.java:2114)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchListener(KafkaMessageListenerContainer.java:1997)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1976)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeIfHaveRecords(KafkaMessageListenerContainer.java:1364)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1355)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1247)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.lang.Thread.run(Thread.java:831)\n",
        "mdc": {
          "id": "CPZPT2S2W_1654441215.694329",
          "context": "tenantId=8554852, appId=101"
        },
        "message": "Failed to handle task.",
        "caller": "com.acme.datalib.messaging.kafka.KafkaConsumer",
        "date": "Mon Jun 06 08:21:26 UTC 2022",
        "thread": "org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1"
      },
      "resource": {
        "type": "k8s_container",
        "labels": {
          "location": "us-central1",
          "cluster_name": "acme-staging",
          "project_id": "acme-stage",
          "pod_name": "reactor-7cd8547b58-mfrbk",
          "namespace_name": "default",
          "container_name": "reactor"
        }
      },
      "timestamp": "2022-06-06T08:21:26.343874838Z",
      "severity": "DEBUG",
      "labels": {
        "k8s-pod/app_kubernetes_io/instance": "reactor",
        "k8s-pod/app_kubernetes_io/name": "reactor",
        "compute.googleapis.com/resource_name": "gke-acme-staging-acme-pool-1c92a002-qq6y",
        "k8s-pod/pod-template-hash": "7cd8547b58"
      },
      "logName": "projects/acme-stage/logs/stdout",
      "receiveTimestamp": "2022-06-06T08:21:27.763967650Z"
    }
  )
```

**Comment by toomanynights** [comment]
I see. Thanks a lot for your help! I think the issue is resolved :)--Sincerely, Basil Vlasyuk10:12 am, 29 October 2023, Liri S ***@***.***>:
Yes, without schema the raw logs will be displayed. The schema is there to parse out specific properties out of the json. i.e the default schema was created with such log lines in mind:
.timestamp [.severity] .jsonPayload.caller .jsonPayload.mdc - .jsonPayload.message - .jsonPayload.e

    {
      "insertId": "hej2q46u808lwlua",
      "jsonPayload": {
        "e": "java.lang.NullPointerException: Cannot invoke \"String.toLowerCase(java.util.Locale)\" because the return value of \"java.net.URI.getHost()\" is null\n\tat com.acme.reactor.utils.PermalinkUtils.sanitizeUrl(PermalinkUtils.java:17)\n\tat com.acme.reactor.nlp.LinksExtractor.handleUrl(LinksExtractor.java:52)\n\tat com.acme.reactor.nlp.LinksExtractor.lambda$extractConversationLinks$0(LinksExtractor.java:30)\n\tat java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)\n\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:3213)\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)\n\tat java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)\n\tat java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)\n\tat java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)\n\tat com.acme.reactor.nlp.LinksExtractor.extractConversationLinks(LinksExtractor.java:22)\n\tat com.acme.reactor.model.Conversation.updateConversationWithMessage(Conversation.java:106)\n\tat com.acme.reactor.model.ConversationsSnapshot.handleMessage(ConversationsSnapshot.java:113)\n\tat com.acme.reactor.service.ConversationHandler.lambda$handleMessage$2(ConversationHandler.java:105)\n\tat java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1940)\n\tat com.acme.reactor.service.ConversationHandler.handleMessage(ConversationHandler.java:101)\n\tat com.acme.reactor.service.MessageEventHandler.handle(MessageEventHandler.java:40)\n\tat com.acme.reactor.messaging.kafka.ReactorKafkaConsumer.lambda$onMessage$1(ReactorKafkaConsumer.java:61)\n\tat com.acme.datalib.messaging.kafka.KafkaConsumer.handleMessage(KafkaConsumer.java:44)\n\tat com.acme.reactor.messaging.kafka.ReactorKafkaConsumer.onMessage(ReactorKafkaConsumer.java:51)\n\tat jdk.internal.reflect.GeneratedMethodAccessor167.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:567)\n\tat org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169)\n\tat org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119)\n\tat org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:56)\n\tat org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:347)\n\tat org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter.invoke(BatchMessagingMessageListenerAdapter.java:180)\n\tat org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter.onMessage(BatchMessagingMessageListenerAdapter.java:172)\n\tat org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter.onMessage(BatchMessagingMessageListenerAdapter.java:61)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchOnMessage(KafkaMessageListenerContainer.java:2268)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchOnMessageWithRecordsOrList(KafkaMessageListenerContainer.java:2258)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchOnMessage(KafkaMessageListenerContainer.java:2204)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchListener(KafkaMessageListenerContainer.java:2114)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchListener(KafkaMessageListenerContainer.java:1997)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1976)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeIfHaveRecords(KafkaMessageListenerContainer.java:1364)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1355)\n\tat org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1247)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.lang.Thread.run(Thread.java:831)\n",
        "mdc": {
          "id": "CPZPT2S2W_1654441215.694329",
          "context": "tenantId=8554852, appId=101"
        },
        "message": "Failed to handle task.",
        "caller": "com.acme.datalib.messaging.kafka.KafkaConsumer",
        "date": "Mon Jun 06 08:21:26 UTC 2022",
        "thread": "org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1"
      },
      "resource": {
        "type": "k8s_container",
        "labels": {
          "location": "us-central1",
          "cluster_name": "acme-staging",
          "project_id": "acme-stage",
          "pod_name": "reactor-7cd8547b58-mfrbk",
          "namespace_name": "default",
          "container_name": "reactor"
        }
      },
      "timestamp": "2022-06-06T08:21:26.343874838Z",
      "severity": "DEBUG",
      "labels": {
        "k8s-pod/app_kubernetes_io/instance": "reactor",
        "k8s-pod/app_kubernetes_io/name": "reactor",
        "compute.googleapis.com/resource_name": "gke-acme-staging-acme-pool-1c92a002-qq6y",
        "k8s-pod/pod-template-hash": "7cd8547b58"
      },
      "logName": "projects/acme-stage/logs/stdout",
      "receiveTimestamp": "2022-06-06T08:21:27.763967650Z"
    }
  )
